### ISSUE TITLE
gvm install go1.9rc1 fail

### ISSUE THREAD

**Issue by acwong00** [moovweb/gvm#272]
I have already install go1.4

```
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /Users/acwong/.gvm/gos/go1.4.1.
failed MSpanList_Insert 0x762a68 0x2750c17f7eb5 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x69e730, 0x762a68)
	/usr/local/go/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Free(0x69e6c0, 0x762a68, 0xc200000000)
	/usr/local/go/src/runtime/mheap.c:500 +0x5b
runtime.MCentral_FreeSpan(0x6a8058, 0x762a68, 0x2, 0xc208088000, 0xc208089000, 0x0, 0x64)
	/usr/local/go/src/runtime/mcentral.c:181 +0x1bb
runtime.MSpan_Sweep(0x762a68, 0x2b00000000, 0x1)
	/usr/local/go/src/runtime/mgc0.c:1096 +0x477
runtime.MHeap_Alloc(0x69e6c0, 0x2, 0x10000000029, 0x79189)
	/usr/local/go/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x6a7e18, 0x3d62a0)
	/usr/local/go/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x75d000, 0x29, 0x800762e78)
	/usr/local/go/src/runtime/mcache.c:90 +0xa0

goroutine 1 [running]:
runtime.switchtoM()
	/usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc2080a4220 sp=0xc2080a4218
runtime.mallocgc(0xc00, 0x0, 0x3, 0xc2080fcd00)
	/usr/local/go/src/runtime/malloc.go:178 +0x849 fp=0xc2080a42d0 sp=0xc2080a4220
runtime.rawmem(0xc00, 0xc00)
	/usr/local/go/src/runtime/malloc.go:371 +0x39 fp=0xc2080a42f8 sp=0xc2080a42d0
runtime.growslice(0x33e500, 0xc2080fcd00, 0x900, 0x900, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:83 +0x237 fp=0xc2080a4358 sp=0xc2080a42f8
go/build.(*importReader).readByte(0xc2080d2c30, 0x20)
	/usr/local/go/src/go/build/read.go:43 +0xd3 fp=0xc2080a43e8 sp=0xc2080a4358
go/build.(*importReader).peekByte(0xc2080d2c30, 0x42dd01, 0x0)
	/usr/local/go/src/go/build/read.go:89 +0x164 fp=0xc2080a4428 sp=0xc2080a43e8
go/build.(*importReader).readKeyword(0xc2080d2c30, 0x47c090, 0x7)
	/usr/local/go/src/go/build/read.go:122 +0x2d fp=0xc2080a4450 sp=0xc2080a4428
go/build.readImports(0x76f7b0, 0xc20802e2c0, 0xc20802e200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/go/build/read.go:207 +0xe7 fp=0xc2080a44a8 sp=0xc2080a4450
go/build.(*Context).matchFile(0x68e820, 0xc2080ed3e0, 0x4f, 0xc2080ed550, 0x6, 0xc2080aa901, 0xc20808af60, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/go/build/build.go:958 +0x5be fp=0xc2080a45f0 sp=0xc2080a44a8
go/build.(*Context).Import(0x68e820, 0x46b4f0, 0x1, 0xc2080304b0, 0x4f, 0x0, 0xc2080304e2, 0x0, 0x0)
	/usr/local/go/src/go/build/build.go:624 +0x1d10 fp=0xc2080a4ee0 sp=0xc2080a45f0
go/build.(*Context).ImportDir(0x68e820, 0xc2080304b0, 0x4f, 0x0, 0x54a580, 0x0, 0x0)
	/usr/local/go/src/go/build/build.go:406 +0x6e fp=0xc2080a4f30 sp=0xc2080a4ee0
main.func·027(0xc2080304b0, 0x4f, 0x76f068, 0xc208031270, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/go/main.go:569 +0x590 fp=0xc2080a5060 sp=0xc2080a4f30
path/filepath.walk(0xc2080304b0, 0x4f, 0x76f068, 0xc208031270, 0xc2080a5820, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:347 +0x91 fp=0xc2080a5198 sp=0xc2080a5060
path/filepath.walk(0xc2080d65f0, 0x48, 0x76f068, 0xc2080d6690, 0xc2080a5820, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:372 +0x51d fp=0xc2080a52d0 sp=0xc2080a5198
path/filepath.walk(0xc20802cd00, 0x3f, 0x76f068, 0xc2080d7180, 0xc2080a5820, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:372 +0x51d fp=0xc2080a5408 sp=0xc2080a52d0
path/filepath.walk(0xc20802ca80, 0x3b, 0x76f068, 0xc2080d7130, 0xc2080a5820, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:372 +0x51d fp=0xc2080a5540 sp=0xc2080a5408
path/filepath.walk(0xc20802c780, 0x32, 0x76f068, 0xc2080d70e0, 0xc2080a5820, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:372 +0x51d fp=0xc2080a5678 sp=0xc2080a5540
path/filepath.Walk(0xc20802c780, 0x32, 0xc2080a5820, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:394 +0xf2 fp=0xc2080a56e0 sp=0xc2080a5678
main.matchPackages(0x7fff5fbff4e4, 0x11, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/go/main.go:577 +0x51e fp=0xc2080a5860 sp=0xc2080a56e0
main.allPackages(0x7fff5fbff4e4, 0x11, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/go/main.go:481 +0x64 fp=0xc2080a5930 sp=0xc2080a5860
main.importPaths(0xc2080ab840, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/go/main.go:329 +0x31b fp=0xc2080a5a28 sp=0xc2080a5930
main.packagesAndErrors(0xc20800a050, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/go/pkg.go:899 +0x1fd fp=0xc2080a5b40 sp=0xc2080a5a28
main.packagesForBuild(0xc20800a050, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/go/pkg.go:919 +0x74 fp=0xc2080a5c50 sp=0xc2080a5b40
main.runInstall(0x6899a0, 0xc20800a050, 0x1, 0x1)
	/usr/local/go/src/cmd/go/build.go:330 +0x55 fp=0xc2080a5d98 sp=0xc2080a5c50
main.main()
	/usr/local/go/src/cmd/go/main.go:163 +0x608 fp=0xc2080a5f98 sp=0xc2080a5d98
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080a5fe0 sp=0xc2080a5f98
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080a5fe8 sp=0xc2080a5fe0

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35
go tool dist: FAILED: /Users/acwong/.gvm/gos/go1.4.1/bin/go install -gcflags=-l -tags=math_big_pure_go -v bootstrap/cmd/...: exit status 2
```
Hope for help

**Comment by tkbky** [comment]
@acwong00 

I'm guessing you're trying to install on Sierra. It's a known [issues](https://github.com/golang/go/issues/16352). A source-only release is released to fix related issues. which you could find it [here](https://golang.org/doc/install/source#go14)

You could try the following:

1. Download & build the source-only release. (https://storage.googleapis.com/golang/go1.4-bootstrap-20170531.tar.gz)
2. Point the `GOROOT_BOOTSTRAP` to it.
3. Then try `gvm install` again.

**Comment by Rukeith** [comment]
@tkbky I still got the problem

**Comment by tkbky** [comment]
@Rukeith Do you mind to elaborate on the problem you have and steps you've taken? Have you tried to install other versions of Go?

**Comment by Rukeith** [comment]
I have try to manual delete .gvm and /usr/local/go. I reinstall gvm or `brew install go` or download pkg from offical website. Every time I run go command, I got this problem. I don't know how to fix this.

**Comment by tkbky** [comment]
AFAIK, there shouldn't be any problem when installing Go via `brew`.
Anyway, could you run the following command and show me the output you have.
```bash
$ go version
$ echo $GOROOT
$ echo $GOROOT_BOOTSTRAP
```

**Comment by Rukeith** [comment]
@tkbky output is below
`/usr/local/go/bin/go`
`go version go1.9.2 darwin/amd64`
`/usr/local/go`
empty

**Comment by tkbky** [comment]
@Rukeith Could you also show me the errors you got?

**Comment by Rukeith** [comment]
I don't know why I reopen my terminal it show up this

    $ go version
    zsh: command not found: go

**Comment by tkbky** [comment]
> $ go version
> zsh: command not found: go

Just check your `zsh` configuration (`~/.zprofile` or `~/.zshrc`), something might have messed up. Btw, this is not related to this issue, so let's not discuss it here, you may understand the problem & find the answer on SO.

**Comment by Rukeith** [comment]
Ok, I will open a new issue for this problem.
